name: penpot01
include:
  - url: https://raw.githubusercontent.com/octocompose/charts/refs/heads/main/penpot/config/all.yaml

configs:
  penpot:
    public_uri: https://penpot.example.com
    flags: disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies
    sizes:
      max_body: "31457280"
      max_multipart_body: "367001600"
    postgres:
      url: postgresql://postgres/penpot
      user: penpot
      password: penpot
  postgres:
    db: penpot
    user: penpot
    password: penpot
  smtp:
    from: penpot@example.com
    reply_to: me@example.com
    host: mail.example.com
    port: 587
    username: penpot
    password: penpot
    tls: true
    ssl: false

octoctl:
  operator: docker