# Service configurations
globals:
  opencloud:
    urls: 
      wopiserver: https://wopiserver.opencloud.test

configs:
  collabora:
    ssl:
      enable: "true"
      verification: "true"
      termination: "true"
      welcome: "false"
    admin:
      user: "admin"
      password: "admin"

octoctl:
  repos:
    collabora:
      url: ../repo/collabora.yaml
  
services:
  traefik:
    networks:
      opencloud-net:
        aliases:
          - "{{.configs.opencloud.domain.collabora}}"
          - "{{.configs.opencloud.domain.wopiserver}}"
  opencloud:
    environment:
      FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR: eu.opencloud.api.collaboration.CollaboraOnline
      GRAPH_AVAILABLE_ROLES: "b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6"
  collaboration:
    entrypoint:
      - /bin/sh
    command: [ "-c", "opencloud collaboration server" ]
    restart: "{{.configs.opencloud.docker.restart}}"
    networks:
      opencloud-net:
    depends:
      opencloud: 
        condition: service_started
      collabora:
        condition: service_healthy
    environment:
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      MICRO_REGISTRY: "{{.configs.opencloud.registry.plugin}}"
      MICRO_REGISTRY_ADDRESS: "{{.configs.opencloud.nats.host}}:{{.configs.opencloud.nats.port}}"
      COLLABORATION_WOPI_SRC: "{{.configs.opencloud.scheme}}://{{.configs.opencloud.domain.wopiserver}}"
      COLLABORATION_APP_NAME: "CollaboraOnline"
      COLLABORATION_APP_PRODUCT: "Collabora"
      COLLABORATION_APP_ADDR: "{{.configs.opencloud.scheme}}://{{.configs.opencloud.domain.collabora}}"
      COLLABORATION_APP_ICON: "{{.configs.opencloud.scheme}}://{{.configs.opencloud.domain.collabora}}/favicon.ico"
      COLLABORATION_APP_INSECURE: "{{.configs.opencloud.insecure}}"
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "{{.configs.opencloud.insecure}}"
      COLLABORATION_LOG_LEVEL: "{{.configs.opencloud.log.level}}"
      OC_URL: "{{.configs.opencloud.scheme}}://{{.configs.opencloud.domain.wopiserver}}"
    volumes:
      # configure the .env file to use own paths instead of docker internal volumes
      - "{{.configs.opencloud.docker.volumes.config}}:/etc/opencloud"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collaboration.entrypoints=https"
      - "traefik.http.routers.collaboration.rule=Host(`{{.configs.opencloud.domain.wopiserver}}`)"
      - "traefik.http.routers.collaboration.tls.certresolver=http"
      - "traefik.http.routers.collaboration.service=collaboration"
      - "traefik.http.services.collaboration.loadbalancer.server.port=9300"
    logging:
      driver: "{{.configs.opencloud.docker.log_driver}}"

  collabora:
    networks:
      opencloud-net:
    environment:
      aliasgroup1: https://{{.configs.opencloud.domain.wopiserver}}:443
      DONT_GEN_SSL_CERT: "YES"
      extra_params: |
        --o:ssl.enable={{.configs.collabora.ssl.enable}} \
        --o:ssl.ssl_verification={{.configs.collabora.ssl.verification}} \
        --o:ssl.termination={{.configs.collabora.ssl.termination}} \
        --o:welcome.enable={{.configs.collabora.ssl.welcome}} \
        --o:net.frame_ancestors={{.configs.opencloud.domain.oc}}
      username: "{{.configs.collabora.admin.user}}"
      password: "{{.configs.collabora.admin.password}}"
    cap_add:
      - MKNOD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabora.entrypoints=https"
      - "traefik.http.routers.collabora.rule=Host(`{{.configs.opencloud.domain.collabora}}`)"
      - "traefik.http.routers.collabora.tls.certresolver=http"
      - "traefik.http.routers.collabora.service=collabora"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"
    logging:
      driver: "{{.configs.opencloud.docker.log_driver}}"
    restart: "{{.configs.opencloud.docker.restart}}"
    command: ["bash", "-c", "coolconfig generate-proof-key ; /start-collabora-online.sh"]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9980/hosting/discovery" ]