projectID: jRganCCBmeSvU6YM5AvLhn

include:
  - url: ./octocompose-chart/config/core.yaml
  - url: ./octocompose-chart/config/traefik.yaml
  - url: ./octocompose-chart/config/posix.yaml
  - url: ./octocompose-chart/config/collabora.yaml

octoctl:
  operator: baremetal


